#Reading Training Values & Renaming the labels descriptively-----------------------------------
X_train<-read.table("X_train.txt")
names(X_train)=paste("feature",1:561,sep = "")
y_train<-read.table("y_train.txt")
names(y_train)="Activity"
subject_train<-read.table("subject_train.txt")
names(subject_train)="subID"
body_acc_x_train<-read.table("body_acc_x_train.txt")
names(body_acc_x_train)=paste("baccX",1:128,sep = "")
body_acc_y_train<-read.table("body_acc_y_train.txt")
names(body_acc_y_train)=paste("baccY",1:128,sep = "")
body_acc_z_train<-read.table("body_acc_z_train.txt")
names(body_acc_z_train)=paste("baccZ",1:128,sep = "")
body_gyro_x_train<-read.table("body_gyro_x_train.txt")
names(body_gyro_x_train)=paste("bgyroX",1:128,sep = "")
body_gyro_y_train<-read.table("body_gyro_y_train.txt")
names(body_gyro_y_train)=paste("bgyroY",1:128,sep = "")
body_gyro_z_train<-read.table("body_gyro_z_train.txt")
names(body_gyro_z_train)=paste("bgyroZ",1:128,sep = "")
total_acc_x_train<-read.table("total_acc_x_train.txt")
names(total_acc_x_train)=paste("taccX",1:128,sep = "")
total_acc_y_train<-read.table("total_acc_y_train.txt")
names(total_acc_y_train)=paste("taccY",1:128,sep = "")
total_acc_z_train<-read.table("total_acc_z_train.txt")
names(total_acc_z_train)=paste("taccZ",1:128,sep = "")
#Reading Test Values & Renaming the labels descriptively
X_test<-read.table("X_test.txt")
names(X_test)=paste("feature",1:561,sep = "")
y_test<-read.table("y_test.txt")
names(y_test)="Activity"
subject_test<-read.table("subject_test.txt")
names(subject_test)="subID"
body_acc_x_test<-read.table("body_acc_x_test.txt")
names(body_acc_x_test)=paste("baccX",1:128,sep = "")
body_acc_y_test<-read.table("body_acc_y_test.txt")
names(body_acc_y_test)=paste("baccY",1:128,sep = "")
body_acc_z_test<-read.table("body_acc_z_test.txt")
names(body_acc_z_test)=paste("baccZ",1:128,sep = "")
body_gyro_x_test<-read.table("body_gyro_x_test.txt")
names(body_gyro_x_test)=paste("bgyroX",1:128,sep = "")
body_gyro_y_test<-read.table("body_gyro_y_test.txt")
names(body_gyro_y_test)=paste("bgyroY",1:128,sep = "")
body_gyro_z_test<-read.table("body_gyro_z_test.txt")
names(body_gyro_z_test)=paste("bgyroZ",1:128,sep = "")
total_acc_x_test<-read.table("total_acc_x_test.txt")
names(total_acc_x_test)=paste("taccX",1:128,sep = "")
total_acc_y_test<-read.table("total_acc_y_test.txt")
names(total_acc_y_test)=paste("taccY",1:128,sep = "")
total_acc_z_test<-read.table("total_acc_z_test.txt")
names(total_acc_z_test)=paste("taccZ",1:128,sep = "")
#Creating TrainDataFrame------------------------------------
train<-data.frame(y_train,subject_train,X_train,body_acc_x_train,body_acc_y_train,body_acc_z_train,body_gyro_x_train,body_gyro_y_train,body_gyro_z_train,total_acc_x_train,total_acc_y_train,total_acc_z_train)
#Creating TestDataFrame--------------------------------------
test<-data.frame(y_test,subject_test,X_test,body_acc_x_test,body_acc_y_test,body_acc_z_test,body_gyro_x_test,body_gyro_y_test,body_gyro_z_test,total_acc_x_test,total_acc_y_test,total_acc_z_test)
#MergingDataframes----------------------------
tidy<-merge(train,test,all = T,na.last=T)
#Converting Activity ID and Subject ID as factors from Integers-----------------
tidy$Activity<-as.factor(tidy$Activity)
tidy$subID<-as.factor(tidy$subID)
conmelt<-melt(tidy,id=c("Activity","subID"),measure.vars = names(tidy)[3:1715])
tidyfinal<-dcast(conmelt,Activity+subID~variable,mean)
